# Generated by Django 5.0.2 on 2024-02-27 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('noofvacancy', models.CharField(max_length=10)),
                ('exp', models.CharField(max_length=50)),
                ('lastdateofapply', models.DateTimeField()),
                ('salary', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
